sudo: required
language: java

branches:
  only:
    - master

services:
  - docker

script: mvn package -B

after_success:
  - docker --version
  - docker build -t rainbowloutre/mep-back .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push rainbowloutre/mep-back;

